In [1]:
# Part A
import numpy as np

# Task 1
matrix = np.random.randint(1, 51, (5, 5))
print("Matrix:\n", matrix)

# Task 2
print("Numbers > 25:\n", matrix[matrix > 25])

# Task 3
modified_matrix = matrix.copy()
modified_matrix[modified_matrix % 2 == 0] = 0
print("Even numbers replaced:\n", modified_matrix)

# Task 4
arr = np.random.randint(1, 100, 10)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized array:\n", normalized)


Matrix:
 [[11 49 40 35 27]
 [43 26 28  8 48]
 [33  3 25  6 15]
 [48 23 45 45 46]
 [25 22 33 14 46]]
Numbers > 25:
 [49 40 35 27 43 26 28 48 33 48 45 45 46 33 46]
Even numbers replaced:
 [[11 49  0 35 27]
 [43  0  0  0  0]
 [33  3 25  0 15]
 [ 0 23 45 45  0]
 [25  0 33  0  0]]
Normalized array:
 [0.12631579 0.         0.84210526 0.89473684 0.77894737 0.50526316
 1.         0.83157895 0.98947368 0.30526316]


In [2]:
import pandas as pd
import numpy as np

# Task 1
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Ravi', 'Priya', 'Amit', 'Sneha', 'Kiran', 'Meena'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'HR', 'Finance'],
    'Age': [25, 30, 28, 35, 40, 29],
    'Salary': [50000, np.nan, 55000, 60000, np.nan, 58000]
}
df = pd.DataFrame(data)

# Task 2
print(df.isnull().sum())

# Task 3
df['Salary'] = df.groupby('Department')['Salary'].transform(lambda x: x.fillna(x.median()))

# Task 4
df['Annual_Bonus'] = df['Salary'] * 0.10
print(df.groupby('Department')['Salary'].mean())


Employee_ID    0
Name           0
Department     0
Age            0
Salary         2
dtype: int64
Department
Finance    56500.0
HR             NaN
IT         55000.0
Name: Salary, dtype: float64


In [3]:
arr = np.arange(1, 21)

# Task 2
matrix = arr.reshape(4, 5)
print(matrix)

# Task 3
print("2nd & 3rd columns:\n", matrix[:, 1:3])

# Task 4
corners = np.array([matrix[0,0], matrix[0,-1], matrix[-1,0], matrix[-1,-1]])
print("Corners:\n", corners)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2nd & 3rd columns:
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
Corners:
 [ 1  5 16 20]


In [4]:
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Printer'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories'],
    'Price': [800, 300, 600, 150, 700],
    'Stock': [10, 100, 30, 15, 5]
}
df = pd.DataFrame(data)

# Task 2
print(df[(df['Price'] > 500) & (df['Stock'] < 50)])

# Task 3
df['Restock_Needed'] = df['Stock'] < 20

# Task 4
print(df.sort_values(by='Price', ascending=False))


   Product     Category  Price  Stock
0   Laptop  Electronics    800     10
2   Tablet  Electronics    600     30
4  Printer  Accessories    700      5
   Product     Category  Price  Stock  Restock_Needed
0   Laptop  Electronics    800     10            True
4  Printer  Accessories    700      5            True
2   Tablet  Electronics    600     30           False
1    Phone  Electronics    300    100           False
3  Monitor  Accessories    150     15            True


In [5]:
# Task 1
temps_c = np.random.uniform(15.0, 40.0, 10)

# Task 2
temps_f = (temps_c * 9/5) + 32

# Task 3
sqrt_arr = np.sqrt(np.arange(1, 11))

# Task 4
print("Index of max temp:", np.argmax(temps_f))


Index of max temp: 8


In [7]:
# Part B
import numpy as np
arr = np.array([10, 25, 30, 45, 60, 15, 50])
# filtered_arr = arr[(arr > 20) and (arr < 50)] (Error)
filtered_arr = arr[(arr > 20) & (arr < 50)]
print(filtered_arr)

[25 30 45]


In [8]:
import pandas as pd
data = {'Employee': ['Ravi', 'Priya', 'Amit'],
        'Department': ['IT', 'HR', 'Finance'],
        'Salary': [50000, 60000, 55000]}
df = pd.DataFrame(data)
# df_dropped = df.drop('Salaries', axis=1) (Error)
df_dropped = df.drop('Salary', axis=1)
print(df_dropped)

  Employee Department
0     Ravi         IT
1    Priya         HR
2     Amit    Finance
